"""
BreatheSafe — Risk Log Model
Stores every PAERI (Personalized Air Exposure Risk Index) calculation.
"""

import enum

from sqlalchemy import JSON, Column, DateTime, Float, ForeignKey, Integer, String
from sqlalchemy import Enum as SAEnum
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.database import Base


class RiskCategoryEnum(str, enum.Enum):
    low      = "Low"
    moderate = "Moderate"
    high     = "High"
    severe   = "Severe"


class RiskLog(Base):
    __tablename__ = "risk_logs"

    id            = Column(Integer, primary_key=True, index=True)
    user_id       = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"),
                           nullable=False, index=True)
    city_id       = Column(Integer, ForeignKey("cities.id"), nullable=True)

    # PAERI score and category
    risk_score    = Column(Float,  nullable=False)           # 0.0 – 1.0+
    risk_category = Column(SAEnum(RiskCategoryEnum), nullable=False)

    # Inputs used for this calculation
    aqi_used           = Column(Float,   nullable=False)     # india_aqi at time
    exposure_hours     = Column(Float,   nullable=True)
    activity_level     = Column(String(20), nullable=True)
    age_used           = Column(Integer, nullable=True)

    # Factor contributions (stored as JSON for explainability)
    # e.g. {"aqi": 0.45, "age": 0.10, "conditions": 0.17, "duration": 0.08}
    factors_json  = Column(JSON, nullable=True)

    # Plain-English explanation generated by explainability agent
    explanation   = Column(String(500), nullable=True)

    timestamp  = Column(DateTime(timezone=True), server_default=func.now(),
                        index=True)

    # Relationships
    user = relationship("User", back_populates="risk_logs")
    city = relationship("City", back_populates="risk_logs")

    def __repr__(self):
        return (f"<RiskLog user={self.user_id} "
                f"score={self.risk_score:.2f} cat={self.risk_category}>")
