"""
BreatheSafe — Route Model
Stores pollution-aware route suggestions generated by the Route Agent.
"""

import enum

from sqlalchemy import JSON, Column, DateTime, Float, ForeignKey, Integer, String
from sqlalchemy import Enum as SAEnum
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.database import Base


class RouteTypeEnum(str, enum.Enum):
    fastest  = "fastest"
    clean    = "clean"       # Least pollution exposure
    balanced = "balanced"    # Trade-off between time and pollution


class TravelModeEnum(str, enum.Enum):
    walking  = "walking"
    cycling  = "cycling"
    driving  = "driving"


class Route(Base):
    __tablename__ = "routes"

    id      = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"),
                     nullable=False, index=True)

    # Source
    source_name = Column(String(200), nullable=True)
    source_lat  = Column(Float, nullable=False)
    source_lon  = Column(Float, nullable=False)

    # Destination
    dest_name   = Column(String(200), nullable=True)
    dest_lat    = Column(Float, nullable=False)
    dest_lon    = Column(Float, nullable=False)

    # Route properties
    route_type           = Column(SAEnum(RouteTypeEnum), nullable=False)
    travel_mode          = Column(SAEnum(TravelModeEnum),
                                  default=TravelModeEnum.driving)
    distance_km          = Column(Float, nullable=True)
    time_min             = Column(Float, nullable=True)
    avg_aqi_exposure     = Column(Float, nullable=True)
    exposure_reduction_pct = Column(Float, nullable=True)  # vs fastest route

    # Full route geometry (GeoJSON LineString from OSRM)
    route_geometry_json  = Column(JSON, nullable=True)

    # Plain-English explanation
    explanation          = Column(String(300), nullable=True)

    # Planned travel window (set when user explicitly saves a route)
    planned_start = Column(DateTime(timezone=True), nullable=True)
    planned_end   = Column(DateTime(timezone=True), nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationship
    user = relationship("User", back_populates="routes")

    def __repr__(self):
        return (f"<Route user={self.user_id} type={self.route_type} "
                f"dist={self.distance_km}km>")
